# 服务端口
server:
  port: 8202

spring:
  profiles:
    active: dev      # 环境设置 ：dev test prod
  application:
    name: service-cmn       #服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmn?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root                    #mysql数据库连接
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8       #返回json的全局时间格式
  redis:
    host: r-bp1juozxsj6kqp8dd5pd.redis.rds.aliyuncs.com
    port: 6379
    password: duhan:LANGhun123456
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5        #最大阻塞时间
        min-idle: 0

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.1.1.1:8848     #nacos服务地址
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858
#  data:
#    mongodb:
#      host: 192.168.44.163
#      port: 27017
#      database: hospotal      #mongodb地址

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest     #rabbitmq地址

#mybatis-plus:
#  mapper-locations: classpath:com/it/appointment_registration/mapper/xml/*.xml   #配置mapper文件的路径

#feign:
#  sentinel:
#    enabled: true   #开启sentinel
#logging:
#  level:
#    root: info
