# 服务端口
server:
  port: 8201

spring:
  profiles:
    active: dev      # 环境设置 ：dev test prod
  application:
    name: service-hosp       #服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospotal?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root                    #mysql数据库连接
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8       #返回json的全局时间格式


#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.1.1.1:8848     #nacos服务地址
#    sentinel:
#      transport:
#        dashboard: http://127.0.0.1:8858
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yygh_hosp      #mongodb地址

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest     #rabbitmq地址

#mybatis-plus:
#  mapper-locations: classpath:com/it/appointment_registration/mapper/xml/*.xml   #配置mapper文件的路径

#feign:
#  sentinel:
#    enabled: true   #开启sentinel
#logging:
#  level:
#    root: info
